### ISSUE TITLE
incomplete implementation of live_marketdata_snapshot() ?

### ISSUE THREAD

**Issue by HaSiMiPa** [Voyz/ibind#1]
Hi Voyz,
amazing work you are doing here. After getting iBeam to work, i started to play with iBind.
I succeeded several API calls, but not live_marketdata_snapshot(). 
It always returns with an Error 500.

Now I looked into your code. Isn't this function supposed to call /iserver/marketdata/snapshot? Yours calls iserver/secdef/search.
While this must be possibly called as pre-flight call (for derivatives), to me it looks this function is not complete. There is also a mandatory  pre-flight call for /iserver/accounts.

Let me know if this makes sense...

**Comment by Voyz** [comment]
Hey @HaSiMiPa, thank you for checking out IBind and creating the first Issue on this repo! 🥳

Here's a celebratory GIF of a happy sheep for you:

![happy-sheep](https://github.com/Voyz/ibind/assets/15874847/02f4aaec-6a1b-4a5a-9931-f1d7be1a345b)

Many thanks for bringing that endpoint into my attention - must have gotten corrupted by accident at some point.

I've just released `v0.1.1` with a fix - let me know if it works for you 👍

**Comment by HaSiMiPa** [comment]
thanks for the quick fix, looks better but now I see the following issue. The call completes well, but the result is missing. I suspect something is wrong with the fields parameter. Example:
Manual browser check works: `/iserver/marketdata/snapshot?conids=265598&fields=31`
it returns the last price (that is: field 31)

when I use iBind, I call 
`my_client.live_marketdata_snapshot('294708433', '31')`
and get
`Result(data=[{'_updated': 1716030999769, 'conidEx': '294708433', 'conid': 294708433}], request={'url': 'https://xxxxx/v1/api/iserver/marketdata/snapshot', 'params': {'conids': '294708433', 'fields': '3,1'}})
`
looks like you put a , (comma) between the 3 and 1.

**Comment by Voyz** [comment]
Glad to hear it worked 👍

As for the mistake you mention - could you clarify it briefly? The `live_marketdata_snapshot` indeed expects a list of arguments. These then get merged together in the following fashion:

```python
params = {
    'conids': ','.join(conids),
    'fields': ','.join(fields)
}
```

What was the issue you were experiencing?

**Comment by HaSiMiPa** [comment]
I just put e.g. '31' as argument with missing quare brackets, instead of correctly ['31'] or ['31, ''80]. 
'31' resulted in a parameter like '3,1'

**Comment by Voyz** [comment]
Ahh, that's a bug too! Thanks for telling me this. The interface in fact supports providing both lists and single arguments. That endpoint was missing that functionality by accident. So yeah, thank you 👏

**Comment by HaSiMiPa** [comment]
@akshayaradhya I don't fuly understand your question. If you ask for an example of the  live_marketdata_snapshot(), here is a simple one:
`client.live_marketdata_snapshot('265598', ['31','55']).data`
Output below.
265598 is the conid for AAPL, 31 is the code for last price, 55 the ticker. You find the codes in the API manual or in the definition file.

```
{'55': 'AAPL',
  '6509': 'D',
  'conidEx': '265598',
  'conid': 265598,
  '_updated': 1716588856195,
  '6119': 'q0',
  'server_id': 'q0',
  '31': '189.99',
```

**Comment by akshayaradhya** [comment]
@HaSiMiPa This is for getting a snapshot. What I needed was, given a ticker - example AAPL, I want to first pull it’s conID (this is easy), after this I want to look for at the money options with same day expiry. And then, I would to find out the conID of a suitable option so I can subscribe to its data

**Comment by Voyz** [comment]
@HaSiMiPa thanks for your example! 👏
@akshayaradhya please see my reply in https://github.com/Voyz/ibind/issues/3 regarding the options chain example, hope it helps

**Comment by HaSiMiPa** [comment]
@akshayaradhya I see. I missunderstood and thought you we asking for options as function parameters :-) I am not trading options, so cannot help here. But Voyz has kindly provided an example already.

**Comment by skkep** [comment]
this is my code:
```
client.receive_brokerage_accounts()
results = client.live_marketdata_snapshot_by_symbol("QQQ",["84","86","31"])
```
it returned no market data,print it just like this:
```
{'QQQ': {}}
```
debuged it, response just included three fields:
```
_updated,conid,conidEx
```
was it the bug of ib?do you have any repair method for this condition. i confirm that i can access account info by api, additionally, i used oauth1a
