### ISSUE TITLE
live_orders() filter parameter

### ISSUE THREAD

**Issue by zacciep** [Voyz/ibind#11]
`live_orders()` has a deafult of `None` for the `filters` parameter. Passing in an argument of `None` raises an exception as it tries to apply the join preprocessing to `None`. An empty string as an argument works. Is this the intended functionality? If I was presented with `None` as a default in the documentation then I would expect to be able to pass `None` in as a valid argument.

**Comment by Voyz** [comment]
Thanks for catching this. When set to `None` the preprocessors will not apply, however due to `@ensure_list_arg` the value of that parameter if it is passed manually as an argument is `[None]` which will cause the preprocessor to trigger. I've fixed it, I'll release it soon.

**Comment by Voyz** [comment]
I'm going to close this as it is now fixed in `0.1.4`. Thanks for contributing 👍
