### ISSUE TITLE
transaction_history()

### ISSUE THREAD

**Issue by zacciep** [Voyz/ibind#13]
This does not work for me. I believe it should be a POST request, not a GET.
https://ibkrcampus.com/ibkr-api-page/cpapi-v1/#pa-transaction-history

**Comment by Voyz** [comment]
Very well spotted! Many thanks for doing all this amazing code review for this project @zacciep 👏

I've just pushed `ibind==0.1.4rc2` with a fix, give it a shot and let me know if it helped 👍

**Comment by zacciep** [comment]
Yes - I am now getting data back for this endpoint. Many thanks...

**Comment by Voyz** [comment]
I'm going to close this as it is now fixed in `0.1.4`. Thanks for contributing 👍
