### ISSUE TITLE
Remove deprecated `distutils` dependency

### ISSUE THREAD

**Issue by teodorkostov** [Voyz/ibind#19]
The dependency:

```
File "/home/user/.local/share/virtualenvs/ibind-project-5ZC5ySRt/lib/python3.12/site-packages/ibind/var.py", line 4, in <module>
  from distutils.util import strtobool
```

`distutils` is deprecated. It is problematic installing it with newer python versions.

Maybe [this](https://stackoverflow.com/questions/77941994/what-is-setuptools-alternative-to-the-deprecated-distutils-strtobool) could help.

**Comment by Voyz** [comment]
Thanks for pointing out, I'll look into alternatives 👍

**Comment by andy145155** [comment]
[This](https://github.com/drgarcia1986/simple-settings/pull/281) might also help

**Comment by Voyz** [comment]
`v0.1.5` has been released addressing this issue. Thanks for your contribution! Feel free to close it 👍

**Comment by Voyz** [comment]
I'm going to close this issue due to inactivity. Thanks for your contribution and please feel free to request a reopen if you'd like to continue the discussion 👍
