### ISSUE TITLE
snapshot_by_key data types

### ISSUE THREAD

**Issue by HaSiMiPa** [Voyz/ibind#2]
in the translation table `snapshot_by_key`  you use string for the key and int for the IDs. As per IB API, the IDs are also of string type.
to me it means:
instead of
`'symbol': 55,  # Symbol`
ist should be
`'symbol': '55',  # Symbol`

**Comment by Voyz** [comment]
Fair point! I made the adjustment and will get this published with the next release. Since this was more of a support function and is not used by the library itself anywhere I sort of just left it as is, but it's good to get it fixed 👍

**Comment by Voyz** [comment]
Indeed! Very good example of how to use it currently.

In my projects I've used that dict by converting to `str` on the fly, seeing it's a miniscule overhead. But it's nice to do it the right way, so thanks for pointing it out 👍

**Comment by Voyz** [comment]
just released `v.0.1.2` with this fix 👍

**Comment by HaSiMiPa** [comment]
confirmed and thanks!
