### ISSUE TITLE
accounts_mixin.py: endpoint urls ?

### ISSUE THREAD

**Issue by posidonius** [Voyz/ibind#20]
Should the starting forward slashes in the endpoint urls ('/iserver/accounts') in accounts_mixin.py be removed?

'''
bind.support.errors.ExternalBrokerError: IbkrClient: response error Result(data=None, request={'url': 'https://localhost:5000/v1/api//iserver/accounts'}) :: 400 :: Bad Request :: {"error":"Bad Request: no bridge","statusCode":400}
'''

**Comment by posidonius** [comment]
Sorry, seems to be my error.

**Comment by Voyz** [comment]
hey @posidonius glad to hear you've figured it out 👍
