### ISSUE TITLE
marketdata_history_by_conid outside_rth boolean issue

### ISSUE THREAD

**Issue by posidonius** [Voyz/ibind#21]
Problem: A call to client.marketdata_history_by_conid() with outside_rth boolean set to True returns market data including outside_rth times.

Possible cause: IBKR Web API seems to expect a boolean value to be in lowercase, as seen here:

Example: "outsideRth="outsideRth=true"
Source: https://ibkrcampus.com/trading-lessons/requesting-market-data/

I have reviewed the ibind code and it seems to pass the boolean directly as a param. I may have missed it, but I don't see where boolean values are converted to lowercase.

That's my theory anyways.

**Comment by posidonius** [comment]
Ignore this, I am wrong again.

**Comment by Voyz** [comment]
And once again I'm happy to hear you've managed to solve it on your own 👏
