### ISSUE TITLE
Where to find the Market Data fields?

### ISSUE THREAD

**Issue by Tsopic** [Voyz/ibind#23]
```
subscription_data = {
    'conid': gc_futures[0]['conid'],
    'fields': [
        FIELD_BID_PRICE,
        FIELD_ASK_PRICE,
        FIELD_BID_SIZE,
        FIELD_ASK_SIZE,
        FIELD_LAST_PRICE,
        FIELD_VOLUME,
    ]
}
```

Saw this example in one of the issues, I've been digging in docs and unable to understand how to bind correct market data fields for the subscription request

Where do I find these values for fields?

**Comment by Voyz** [comment]
Hey @Tsopic thanks for describing your issue 👍

You can find these here:

https://www.interactivebrokers.com/campus/ibkr-api-page/cpapi-v1/#market-data-fields

Or indirectly in IBind, in ibkr_definitions.py (though note that these are manually typed in and may become out of date at some point):

https://github.com/Voyz/ibind/blob/master/ibind/client/ibkr_definitions.py

Let me know if that helps 👍
