### ISSUE TITLE
Please add some examples

### ISSUE THREAD

**Issue by akshayaradhya** [Voyz/ibind#3]
Hi,

Really appreciate the efforts in making this library. I have been wrestling with IBKR since quite a while and it’s great to see libraries like this that simplify some things. Could you please add some common examples? It’s really not that straightforward for someone who’s not familiar with rest API and web sockets. Here are the examples I would highly appreciate. 

- Searching for a stock and qualifying the contract 
- Getting current price of a contract
- Pulling the options chain, given a ticker 
- Selecting a certain contract from the given options chain
- Subscribing to the market data through web socket for a given contract 
- Subscribing to real time bars through web socket, given a contract 
- Placing market order for a given contract
- Scheduling a callback at a given time

Would highly appreciate it if the examples are made available in the repo. The ones that are given already, are not really that straightforward for someone who’s not familiar with this ecosystem. 

Thanks 🙏🏽

**Comment by Voyz** [comment]
Hey @akshayaradhya thank you for the kind words and for trying IBind out.

As for the examples, you write the following:

> The ones that are given already, are not really that straightforward for someone who’s not familiar with this ecosystem.

Hence I assume you've already seen the [Examples](https://github.com/Voyz/ibind/tree/master/examples) section? 

There indeed you'll find a bunch of the examples you request:

- ✅ Searching for a stock and qualifying the contract
- ✅ Getting current price of a contract
- ❌ Pulling the options chain, given a ticker
- ❌ Selecting a certain contract from the given options chain
- ✅ Subscribing to the market data through web socket for a given contract
- ✅ Subscribing to real time bars through web socket, given a contract
- ✅ Placing market order for a given contract
- ❌ Scheduling a callback at a given time

Therefore:
1. You've listed a few examples that are currently present. What are you missing in the existing examples? You write that they are not that straightforward - I'm sorry to hear that. In fact I tried to keep the examples as straightforward as possible, yet unfortunately several interaction with the API are a bit more complex and currently require a more code to carry out. Could you elaborate here as to what was not straightforward in the existing examples? 
1. As for the option chains - that example is not currently implemented. I appreciate you making the request.
1. As for scheduling a callback - do you mean just a normal scheduled Python callback or is there a IBKR callback functionality that you refer to here?

**Comment by HaSiMiPa** [comment]
Hey @akshayaradhya I also recently started to use iBind. Honestly, I have little problems to use it as it is very well documented. What I can suggest that may help you as it helped me:
- read through the [IB WEB API documentation](https://ibkrcampus.com/ibkr-api-page/webapi-ref/) there are many good examples and paramter description
- play with the rest API directly in the browser, as simple as: https://yourserver:port/v1/api/portfolio/accounts I assume you have the connection already in place. Chrome gives you a nice structured output
- check out iBind sources - it gives you a good idea how REST calls are translated to the functions
- start simple with just reading your account data or positions, enhance from there
- have fun :-)

**Comment by Voyz** [comment]
I've just added the new [`rest_06_options_chain.py`](https://github.com/Voyz/ibind/blob/master/examples/rest_06_options_chain.py) example which should hopefully address the first two requests you made.

As for the scheduling a callback - unfortunately IBind doesn't have such functionality built in. However, please find the following snippet of code for carrying out such operation yourself easily:

```python
import threading
import time


def run_callback_after_delay(callback, delay):
    """Runs the callback function after a specified delay.

    Args:
        callback (function): The function to be executed after the delay.
        delay (float): The delay time in seconds before executing the callback.
    """
    timer = threading.Timer(delay, callback)
    timer.start()

# Example usage:
def my_callback():
    print("Callback executed!")

run_callback_after_delay(my_callback, 5)  # Executes my_callback after 5 seconds

for i in range(6):
    time.sleep(1)
    print(f'{i+1}s passed...')
```

Should output:
```
1s passed...
2s passed...
3s passed...
4s passed...
5s passed...
Callback executed!
6s passed...
```

Hope these help 👍

**Comment by akshayaradhya** [comment]
@Voyz Thank you very much for the example. Highly appreciate it. I improved the example by a bit. The below example finds n contracts with closest strikes to the current price of the underlying expiring on the immediate trading day. Hope it helps :)

Thanks again! Will continue using the library and give you more feedback  

`"""
REST options chain

In this example we:

* Retrieve an options chain for QQQ

Assumes the Gateway is deployed at 'localhost:5000' and the IBIND_ACCOUNT_ID and IBIND_CACERT environment variables have been set.
"""

import os
from ibind import IbkrClient, ibind_logs_initialize
from pprint import pprint
from datetime import datetime

def find_next_maturity(data_list):
    # Define the format of the date strings
    date_format = "%Y%m%d"
    
    # Get today's date dynamically
    today = datetime.now()
    
    # Filter and sort the list of dictionaries by their maturityDate
    future_dates = [item for item in data_list if datetime.strptime(item['maturityDate'], date_format) >= today]
    
    if not len(future_dates):
        print("No contracts found!")
        return None
    
    next_item = min(future_dates, key=lambda x: datetime.strptime(x['maturityDate'], date_format))
    
    return next_item

def find_n_closest_strikes(input_list, value, n):
    # Calculate the absolute difference from the given value for each number in the list
    differences = [(abs(num - value), num) for num in input_list]
    
    # Sort the list based on the calculated differences
    sorted_by_difference = sorted(differences, key=lambda x: x[0])
    
    # Extract the top n closest numbers
    closest_strikes = [num for _, num in sorted_by_difference[:n]]
    
    return sorted(closest_strikes)

ibind_logs_initialize()

cacert = os.getenv('IBIND_CACERT', False)  # insert your cacert path here
client = IbkrClient(cacert=cacert)


print('\n#### search for contract ####')
contracts = client.search_contract_by_symbol('QQQ').data
contract = contracts[0]
pprint(contract)


# find the options section in contract
options = None
for section in contract['sections']:
    if section['secType'] == 'OPT':
        options = section
        break

if options is None:
    raise RuntimeError(f'No options found in contract: {contract}')


expiry = options['months'].split(';')[0]

print('\n#### search for strikes ####')
strikes = client.search_strikes_by_conid(
    conid=contract['conid'],
    sec_type='OPT',
    month=expiry
).data
print(str(strikes).replace("'put'", "\n'put'"))

curr_price = float(client.live_marketdata_snapshot(contract['conid'],['31']).data[0]['31'])

closest_strikes = find_n_closest_strikes(strikes['call'], curr_price, 5)

print('\n#### validate contracts ####')
for strike in closest_strikes:
    for right in ['C','P']:
        info = client.search_secdef_info_by_conid(
            conid=contract['conid'],
            sec_type='OPT',
            month=expiry,
            strike=strike,
            right=right
        ).data
        pprint(find_next_maturity(info))`

**Comment by Voyz** [comment]
Great, happy to help 😊 And thanks for sharing your example too 👍

**Comment by rmalh** [comment]
Thank you so much for sharing ibind with us! I'm new to it and am trying to port my strategy over from the TWS API to ibind. My apologies if I missed it but I have not been able to find the equivalent of the following:

- openOrders()
- trades()
- qualifyContracts()
- how to get the current bid-ask midpoint for a security
- how to set the exchange for a contract to 'SMART'

Would you mind pointing me to the equivalent methods in ibind and/or relevant resources where they have been discussed?

TIA!

**Comment by Voyz** [comment]
Hey @rmalh thanks for bringing this up, and my apologies for forgetting to get back to you on Reddit - you did right in bringing the discussion here.

Let me address the points you've raised, although please be aware that for some functionalities there isn't a 1 to 1 mapping between TWS and Web API. 

> openOrders

https://github.com/Voyz/ibind/wiki/API-Reference-%E2%80%90-IbkrClient#client.ibkr_client_mixins.order_mixin.OrderMixin.live_orders

> trades()

As in your own trades? If so then have a look at:

https://github.com/Voyz/ibind/wiki/API-Reference-%E2%80%90-IbkrClient#client.ibkr_client_mixins.portfolio_mixin.PortfolioMixin.transaction_history

Or at WebSocket TRADES channel:

https://github.com/Voyz/ibind/wiki/API-Reference-%E2%80%90-IbkrWsClient#client.ibkr_ws_client.IbkrWsKey

> qualifyContracts()

Not entirely sure, I remember using this with TWS but it was a while ago. Could you outline what it does?

> how to get the current bid-ask midpoint for a security

https://github.com/Voyz/ibind/wiki/API-Reference-%E2%80%90-IbkrClient#client.ibkr_client_mixins.marketdata_mixin.MarketdataMixin.live_marketdata_snapshot

> how to set the exchange for a contract to 'SMART'

Depends for what? Some endpoints accept the 'exchange' or 'conidex' parameters which is where you'd be able to specify it. I think by that _'for a contract'_ you mean a similar pattern as in TWS, where you'd create a contract object and then use it to operate on the API (again, it's been a while since I've used TWS API so forgive me if I'm remembering incorrectly). I don't think this is the expected way to use the Web API - you just specify the exchange when it is made available as an endpoint parameter. Other than that, you just use conids.

----

Hope these answers help, any more questions let me know 👍
