### ISSUE TITLE
RFI - Symbol Margin Requirements (possible ER).

### ISSUE THREAD

**Issue by GonzRon** [Voyz/ibind#32]
**Describe the feature**
If you trade futures, you know the margin required may often change. It’s particularly true for IB: being a rather conservative broker, they apply an extra margin required on any contract on top of what is typically dictated by the exchange. Keeping up to date with their latest margins required is a bit of a pain. You’d  need to look on their webpage and scroll between dozens and dozens of contracts, at least weekly if you run multiple algos. 

https://www.interactivebrokers.com/en/trading/margin-futures-fops.php

I did take a look at the official WebApi Documentation, specifically: [WebApi Querying Equity and Margin](https://www.interactivebrokers.com/campus/ibkr-api-page/webapi-doc/#querying-equity-and-margin-38).  However, this seems to be related to the account's usage of margin, rather than the margin requirements for a symbol in particular.  Perhaps the webApi supports this already on instruments, i.e. you can get a ‘live quote’ on the required margin for a given product, however I did not find that capability in their API Docs, so I am not aware of this in webApi, and did not bother looking at TWSAPI documentation.

If the IB webApi does not currently support this, this sample code below can potentially serve as the backend for a new IBeam API call.  It could be configured to scrape the site periodically, and maintain a local cache with this information that can be easily queried.  Or perhaps, the data could simply be added as a new field to the existing symbol lookup data return object?  (i.e. the margin required for the symbol).

Here’s the script:

```
import tkinter as tk
from tkinter import ttk, messagebox
import requests
from bs4 import BeautifulSoup
import csv


def get_margin_requirements(ticker_list):
    """
    Fetches margin requirements for a list of tickers from the Interactive Brokers website.

    Args:
        ticker_list (list): A list of tickers for which to fetch margin requirements.

    Returns:
        list: A list of tuples, each containing the ticker and its margin requirement.
    """
    url = "https://www.interactivebrokers.com/en/trading/margin-futures-fops.php"
    response = requests.get(url)
    if response.status_code != 200:
        print(f"Failed to retrieve the webpage. Status code: {response.status_code}")
        return []

    # Parse the content with BeautifulSoup and locate all rows in tables
    soup = BeautifulSoup(response.content, 'html.parser')
    rows = soup.select('table tr')  # Select all table rows directly for efficiency
    margin_data = []

    # Filter and extract margin requirements based on tickers
    for row in rows:
        cells = row.find_all(['td', 'th'])
        if len(cells) >= 7:
            ticker = cells[3].get_text(strip=True)
            if ticker in ticker_list:
                margin_required = cells[6].get_text(strip=True)
                margin_data.append((ticker, margin_required))

    return margin_data


def fetch_margins():
    # Get tickers from entry, ensuring uppercase and no duplicates
    tickers = list(set(ticker.strip().upper() for ticker in ticker_entry.get().split(',') if ticker.strip()))

    if not tickers:
        messagebox.showerror("Input Error", "Please enter at least one ticker.")
        return

    # Fetch and display unique margin requirements
    margin_requirements = get_margin_requirements(tickers)
    unique_margins = {ticker: margin for ticker, margin in margin_requirements}

    # Clear the existing rows and populate with new data
    margin_tree.delete(*margin_tree.get_children())
    for ticker, margin in unique_margins.items():
        margin_tree.insert("", "end", values=(ticker, margin))

    if not unique_margins:
        messagebox.showinfo("No Data", "No margin data found for the specified tickers.")


def export_to_csv():
    # Export Treeview data to CSV
    rows = margin_tree.get_children()
    if not rows:
        messagebox.showwarning("No Data", "No data available to export.")
        return

    with open("margin_requirements.csv", "w", newline="") as file:
        writer = csv.writer(file)
        writer.writerow(["Ticker", "Margin Required"])  # Header
        writer.writerows(margin_tree.item(row)["values"] for row in rows)

    messagebox.showinfo("Export Successful", "Data exported to margin_requirements.csv successfully.")


# Main application setup
app = tk.Tk()
app.title("Margin Requirements App")
app.geometry("500x500")

# UI Elements
tk.Label(app, text="Enter tickers (comma-separated):").pack(pady=5)
ticker_entry = tk.Entry(app, width=50)
ticker_entry.pack(pady=5)

# Buttons
button_frame = tk.Frame(app)
button_frame.pack(pady=10)
tk.Button(button_frame, text="Fetch Req Margins", command=fetch_margins).pack(side="left", padx=5)
tk.Button(button_frame, text="Export to .CSV", command=export_to_csv).pack(side="left", padx=5)

# Data display
margin_tree = ttk.Treeview(app, columns=("Ticker", "Margin Required"), show="headings", height=10)
margin_tree.heading("Ticker", text="Ticker")
margin_tree.heading("Margin Required", text="Margin Required")
margin_tree.pack(pady=20)

# Run the application
app.mainloop()
```

Thanks to a fellow trader Davide for the write up and the code!

**Comment by Voyz** [comment]
Hi @GonzRon many thanks for sharing your idea and your code 👏

Just to start:

1. You mention you've tried looking through the WebAPI docs. By that I assume you looked through the WebAPI V1.0 (CP Web API) and not the new Web API. Seeing that you didn't find it there, did you try contacting IBKR to find out if they provide an API to query this? If not, it could be a good idea to check with them first.
2. Could I ask you to reformat the code you've shared? The indentation seems to be all off.

**Comment by GonzRon** [comment]
> Hi @GonzRon many thanks for sharing your idea and your code 👏
> 
> Just to start:
> 
> 1. You mention you've tried looking through the WebAPI docs. By that I assume you looked through the WebAPI V1.0 (CP Web API) and not the new Web API. 
Incorrect assumption, although that would have been the smart thing to do.  I looked through the new webApi docs.  Though the API 1.0 docs also do not feature this capability.  So it's a nill point anyways.
> Seeing that you didn't find it there, did you try contacting IBKR to find out if they provide an API to query this? If not, it could be a good idea to check with them first.
I did not, and I probably don't plan on doing so ATM, not that important.
> 2. Could I ask you to reformat the code you've shared? The indentation seems to be all off.
Yes, absolutely, of course, here's a more complete solution:
```
import requests
from bs4 import BeautifulSoup
import pandas as pd

URL = "https://www.interactivebrokers.com/en/trading/margin-futures-fops.php"


def extract_futures_margin_tables(URL=URL):
    response = requests.get(URL)
    response.raise_for_status()  # Check if the request was successful
    soup = BeautifulSoup(response.text, 'html.parser')

    # Dictionary to store all tables
    margin_tables = {}

    # Find all table sections with headings
    table_sections = soup.find_all('div', {'class': 'table-responsive'})

    for section in table_sections:
        # Try to find the closest heading above the table
        header = None
        current = section
        while current and not header:
            # Look for h5 (exchange names are in h5 tags)
            header_elem = current.find_previous_sibling('h5')
            if header_elem:
                header = header_elem.text.strip()
                break
            current = current.parent

        if not header:
            continue

        # Find the table in this section
        table = section.find('table')
        if not table:
            continue

        # Extract table headers
        headers = []
        for th in table.find_all('th'):
            headers.append(th.text.strip())

        # Extract table rows
        rows = []
        for tr in table.find_all('tr')[1:]:  # Skip header row
            row = []
            for td in tr.find_all('td'):
                row.append(td.text.strip())
            if row:  # Only add non-empty rows
                rows.append(row)

        # Convert to DataFrame for easier handling
        df = pd.DataFrame(rows, columns=headers)

        # Store in dictionary
        margin_tables[header] = df

    return margin_tables


# Function to display table info
def print_table_summary(tables_dict):
    print(f"Found {len(tables_dict)} tables:")
    for exchange, df in tables_dict.items():
        print(f"\n{exchange}")
        print(f"Dimensions: {df.shape}")
        print("Columns:", list(df.columns))
        print("First few rows:")
        print(df.head(2))
        print("-" * 80)


if __name__ == "__main__":
    tables = extract_futures_margin_tables(URL)
    print_table_summary(tables)
```

**Comment by Voyz** [comment]
Hey @GonzRon I think I understand what you were trying to do here. Thanks for expanding on your answers. And I'm sorry to see that you found some other limitations that prohibited you from going forward. Would you be able to share what these are?

**Comment by GonzRon** [comment]
Specifically the inability to retrieve historical data for continuous futures symbols.

**Comment by Voyz** [comment]
Thanks for sharing and I'm sorry to hear that. Best of luck! Feel free to close this issue when ready

**Comment by GonzRon** [comment]
> Thanks for sharing and I'm sorry to hear that. Best of luck! Feel free to close this issue when ready

![image](https://github.com/user-attachments/assets/4a7ae751-6ed3-4849-b0fe-258030414174)

**Comment by Voyz** [comment]
hey @GonzRon not sure how to interpret that screenshot - is that a good thing or a bad thing?

**Comment by GonzRon** [comment]
I dont know @Voyz you tell me?
