### ISSUE TITLE
Portfolio 2 - Update to Positions Request

### ISSUE THREAD

**Issue by climbercarmich** [Voyz/ibind#8]
https://ibkrcampus.com/ibkr-api-page/cpapi-v1/#positions

IBKR have just made available a new version of Portfolio Positions that gives near real time updates on the position fields. It would be great to have this available within ibind.

**Comment by Voyz** [comment]
Hey @climbercarmich thanks for spotting this and for making the suggestion 👏👏

I've just released `v0.1.3` with that endpoint supported. Note that the documentation states that `pageId` query parameter is supported, however the endpoint itself seems to not work when it is provided. The current implementation doesn't have `page_id` parameter.

https://pypi.org/project/ibind/0.1.3/

Let me know if it works for you 👍

**Comment by HaSiMiPa** [comment]
Perfect. Works for me. Thanks @climbercarmich for spotting!

**Comment by Voyz** [comment]
I'm going to close this Issue since it was addressed and implemented. Thanks!
