### ISSUE TITLE
conid parameter in 'make_order_request' function

### ISSUE THREAD

**Issue by zacciep** [Voyz/ibind#9]
I believe conid needs to be an int, not a str.

**Comment by zacciep** [comment]
Note that the 'live_market_data' method checks its parameters and requires a str (as it builds a list).

**Comment by Voyz** [comment]
Hey @zacciep thanks for pointing it out. I've modified the `make_order_request` as per your suggestions. I'll publish it with the next minor release.

As for the `live_market_data` - I'm sorry but IBind doesn't have such a method. If you meant the `live_marketdata_snapshot` method, it indeed expects strings as it builds a list as you describe. I'm not sure I understand the message behind what you wrote - could you elaborate?

**Comment by zacciep** [comment]
I was just pointing out the inconsistency between the need for conid as an int to get ‘make_order_request’ and ‘place_order’ to work, vs ‘live_marketdata_snapshot’ actively insisting on conid as a str. Do you have an approach of keeping parameters in the same format as IBKR within IBind, or converting them on request? If the former, then for consistency should ’live_marketdata_snapshot’ take the conids as a list of ints (and convert them into a str itself)?None of this is helped by IBKR’s interface which is terribly inconsistent with parameter names and formatting. It makes me want to cry!My one remaining issue is ‘transaction_history’, where the server is complaining of a bad request saying that ‘account_id’ is missing, even though it is in the list of account_ids and the request query and parameters seem to be exactly formatted as their examples on their documentation. Can’t see anything wrong. May be a server side problem. Have you been able to make this function call / request work?ZacOn 22 Jun 2024, at 08:20, voyz ***@***.***> wrote:﻿
Hey @zacciep thanks for pointing it out. I've modified the make_order_request as per your suggestions. I'll publish it with the next minor release.
As for the live_market_data - I'm sorry but IBind doesn't have such a method. If you meant the live_marketdata_snapshot method, it indeed expects strings as it builds a list as you describe. I'm not sure I understand the message behind what you wrote - could you elaborate?

**Comment by Voyz** [comment]
Understood, thanks for clarifying. Truth is, the API seems to accept both `str` and `int`. I know they specify just one or the other, but I never saw a request rejected for that reason.

That being said, it probably is a good idea to introduce more consistency there. I'll look into it at some point when I find a minute

**Comment by Voyz** [comment]
`v0.1.5` has been released adding consistency to conid params. Thanks for your contribution! Feel free to close this issue 👍
